# Generated by Django 3.2.9 on 2021-12-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(verbose_name='Входные данные')),
                ('finish', models.TextField(verbose_name='Обезличенные данные')),
                ('data', models.DateTimeField(verbose_name='Дата ввода')),
            ],
        ),
    ]
