# Generated by Django 3.2.9 on 2021-12-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
    ]
