# Generated by Django 3.2.9 on 2021-12-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='data',
        ),
    ]
